site_name: Yun download
site_url: https://yunhai-dev.github.io/yundownload/
repo_url: https://github.com/yunhai-dev/yundownload
copyright: Copyright 2021-2025
repo_name: yunhai-dev/yundownload

nav:
  - 介绍: "index.md"
  - 快速入门(0.6.X): "v6-quickstart.md"
  - 快速入门(0.4.X): "v4-quickstart.md"
  - 快速入门(0.3.X): "v3-quickstart.md"
  - 快速入门(0.2.X): "v2-quickstart.md"

theme:
  name: material
  features:
    - navigation.tabs
  language: zh

plugins:
  - git-revision-date-localized
  - search:
      lang: ru

# mkdocs gh-deploy 提交到git pages
# pip install mkdocs
# pip install mkdocs-material
# pip install mkdocs-git-revision-date-localized-plugin